version: '3.8'
services:
  front:
    build:
      context: ./
      target: dev
    volumes:
      - ./src:/front/src
      - ./public:/front/public
    command: npm run start
    ports:
      - "3000:3000"
    networks:
      - dockerlan
    restart: always

networks:
  dockerlan:
    driver: bridge
