version: '3.8'
services:
  front:
    build:
      context: ./
      target: production
    command: npm run build
    ports:
      - "3000:3000"
    networks:
      - dockerlan
    restart: always

networks:
  dockerlan:
    driver: bridge
